name: Windows CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Vulkan SDK
      run: |
        Invoke-WebRequest https://vulkan.lunarg.com/sdk/home#sdk/downloadConfirm/1.1.126.0/windows/VulkanSDK-1.1.126.0-Installer.exe -OutFile VulkanSDK-1.1.126.0-Installer.exe
        .\VulkanSDK-1.1.126.0-Installer.exe /S
    - name: Compile vcpkg dependencies
      run: .\vcpkg_windows.bat
    - name: Compile raytracer
      run: .\build_windows.bat
