name: Windows CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    env:
      VULKAN_SDK: C:\VulkanSDK\1.1.126.0

    steps:
    - uses: actions/checkout@v1
    - name: Download Vulkan SDK
      run: Invoke-WebRequest "https://sdk.lunarg.com/sdk/download/1.1.126.0/windows/VulkanSDK-1.1.126.0-Installer.exe?Human=true" -OutFile VulkanSDK.exe -v
    - name: Install Vulkan SDK
      run: .\VulkanSDK.exe /S
      shell: cmd
    - name: Check Vulkan SDK
      run: |
        dir
        dir C:\
        dir C:\VulkanSDK
        dir C:\VulkanSDK\1.1.126.0
        set
    - name: Compile vcpkg dependencies
      run: vcpkg_windows.bat
      shell: cmd
    - name: Compile raytracer
      run: build_windows.bat
      shell: cmd
