name: Windows CI

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest
    env:
      VULKAN_SDK: C:\VulkanSDK\1.1.126.0

    steps:
    - uses: actions/checkout@v1
    - name: Download Vulkan SDK
      run: Invoke-WebRequest "https://sdk.lunarg.com/sdk/download/1.1.126.0/windows/VulkanSDK-1.1.126.0-Installer.exe?Human=true" -OutFile VulkanSDK.exe -v
    - name: Install Vulkan SDK
      run: .\VulkanSDK.exe /S
      shell: cmd
    - name: Check Vulkan SDK
      run: |
        dir
        dir C:\
        dir C:\VulkanSDK
        dir C:\VulkanSDK\1.1.126.0
        set
      shell: cmd
    - name: Compile vcpkg dependencies
      run: vcpkg_windows.bat
      shell: cmd
    # This is where GitHub actions on Windows get really nonsensical.
    # MSBuild is not on the path by default, despite this running on a Windows / Visual Studio 2019 docker image.
    # We currently use 3rd party action to avoid hard coding the path to MSBuild.
    # Comedy bonus: GitHub is now owned by Microsoft.
    - name: Setup MSBuild
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Compile raytracer
      run: build_windows.bat
      shell: cmd
